name: Deploy Cloud Function

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to Cloud Functions (Gen 2)
      run: |
        gcloud functions deploy load_data_to_bigquery \
          --gen2 \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --region ${{ secrets.GCP_REGION }} \
          --entry-point load_data_to_bigquery \
          --memory 16Gi \
          --timeout 3600s \
          --cpu 4 \
          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Verify Deployment
      run: |
        gcloud functions describe load_data_to_bigquery \
          --region ${{ secrets.GCP_REGION }} \
          --gen2 \
          --project ${{ secrets.GCP_PROJECT_ID }}